### ISSUE TITLE
Create Lists of Competencies and Tracking Location

### ISSUE THREAD

**Issue by mattbusch** [cking90/excel-tracker#36]
- [ ] Create Tracking Location List
- [ ] Create Competencies List
- [ ] Add link to competencies page
- [ ] Add link to Tracking Location
